### ISSUE TITLE
It's really OK to throw exceptions?

### ISSUE THREAD

**Issue by yanni4night** [justjohn/twig.js#121]
I'am sorry but I really doubt that throwing exceptions is OK for node.js,because these could not be catched,and fails the http server.

What about a tay-catch block around the 'compile' function?

**Comment by evgenius** [comment]
Seems to be fixed via https://github.com/justjohn/twig.js/commit/2ca7cb0fe19ce0dcdbb5f5a73e598964e6d05e41
