### ISSUE TITLE
Twig.js requires optimization of a "for" tag

### ISSUE THREAD

**Issue by evgenius** [justjohn/twig.js#144]
We noticed a significant lag in the UI of our application.
We discovered that the "for" tag is not optimized for big contexts and when there's a lot of loops in the template.
The reason is the context being copied in every loop's body.
I.e. if you have 10 loops for an array of size 100, your context is copied for 1000 times.
It can take much time if the context is big.

**Comment by evgenius** [comment]
https://github.com/justjohn/twig.js/commit/0282845a0cd41972f710bcffdfd89cb933205edd
Looks like we never merged it to the master :(
Anyway, going to change the way it works to avoid copying the context.

**Comment by fourpixels** [comment]
What's up with this one? Don't see it in master, and I find it very important!

**Comment by evgenius** [comment]
Hi @fourpixels, we optimized performance in 0.8.2. It's released already.
