### ISSUE TITLE
Question: is it possible to preload all the twig templates?

### ISSUE THREAD

**Issue by ruffle1986** [justjohn/twig.js#146]
Sorry if it's a duplicated question but I couldn't find the right answer neither in the issues nor in Google.

I would like to preload all the twig templates (even that are included in other twig templates by 'include' operator) to reduce individual xhr requests during our application's  lifetime. 

If it's not supported by default, can you suggest a good approach to handle this?

**Comment by webberig** [comment]
I use following Grunt task which does exactly what you want:
https://github.com/adamdicarlo/grunt-twig

It precompiles all configured twig templates and generates a single Javascript file. This also means you don't need to compile them client-side.

**Comment by ruffle1986** [comment]
thanks. :)
