### ISSUE TITLE
Multiline include

### ISSUE THREAD

**Issue by jeremieca** [justjohn/twig.js#158]
Hey !

Thanks to port twig on javascript.

It seems include must be on called on a single line.

        {% include 'partial/mail_button_layout.html.twig' with {"button_name": 'Confirmer mon inscription', "button_href": 'http://localhost:8080', "separator": true } %}

I would like to do that

        {% include 'partial/mail_button_layout.html.twig' with {
	        "button_name": "Confirmer mon compte",
	        "button_href": 'http://localhost:8080',
	        "separator": true
        } %}

Is it possible ?

Jérémie C.

**Comment by brunowego** [comment]
+1

**Comment by tomfun** [comment]
+1

**Comment by jmsbrr** [comment]
+ 1

**Comment by evgenius** [comment]
I just tested this case. Yes, it's supported.

**Comment by evgenius** [comment]
Except you're not using a remote template but specifying it in the JS source.
Then you need to add a backslash before the newline break:
```
var template = '{% import template with {\
  "foo": "bar"\
} %}';
```

It's just how JavaScript works.
