### ISSUE TITLE
Variable scoping error

### ISSUE THREAD

**Issue by csimi** [justjohn/twig.js#167]
It seems like there's a problem with variable scoping.
The following example has different outputs in the php and js version (tested in 0.7.2):

```twig
{% set x = 'x' %}
{% for i in range(0, 5) %}
	y
	{% set x = 'z' %}
	{{ x }}
{% endfor %}
{{ x }}
```

Output in PHP: y z y z y z y z y z y z z
Output in JS: y z y z y z y z y z y z x

x should keep the value as z.

**Comment by evgenius** [comment]
Tested in 0.8.2: works fine now.
