### ISSUE TITLE
Errors are reported via console.log, why not use console.error ?

### ISSUE THREAD

**Issue by paulgreg** [justjohn/twig.js#174]
Twig.log.error = function() {
       console.log.apply(console, arguments);
    }

When declaring [Twig.log.error](https://github.com/justjohn/twig.js/blob/master/src/twig.core.js#L150) function, why is it using console.log ?
Shouldn’t it be using console.error (if avaible) ?

It’s problematic in my case because I’ve got error reported by node in "out" log file and not into the "err" one.

**Comment by evgenius** [comment]
Fixed via #175
