### ISSUE TITLE
Iteration problem in nested loops

### ISSUE THREAD

**Issue by meefox** [justjohn/twig.js#191]
Looks like there is an issue with scoping variable in loops
```
{% set k = 0 %}
{% for i in 0..5%}
	{% for j in 0..5 %}
		{{ k }}
		{% set k = k + 1 %}
	{% endfor %}
{% endfor %}
```
I expect that it will iterate by 1 each time.
Like 0,1,2,3,4,5,6 and so on, but it is 0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,3 and so on.

**Comment by evgenius** [comment]
Tested in 0.8.2: works fine now.
