### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by George02** [justjohn/twig.js#206]
I'm creating an express application and for the views render I use twig.js.

I'm displaying some posts from `mongodb` into `index.twig` file. The question is `how can I call a function from a js file`(let's call it Utils.js) `in the twig file?`

My index.twig file looks something like this:

`<div class="post-date">{{ post["date"] }}</div>`
`<div class="post-body">`
`    {{ post["body"] }}`
`</div>`

What I need to do is to format that post["date"] calling a method from Utils.js not just echoing it out as it is. How can I do that ?

P.S. I know that there are filters for date but I want my own data format.

EDIT: I can do it with filters if there's one that will modify the F to be language specific. So F will echo February but I want it to be on my language.(ro_RO) `{{ post["date"]|date("d F Y", "Europe/Bucharest") }}`

**Comment by evgenius** [comment]
Hi @George02 ,

To add a filter you can use `Twig.extendFilter()`:
```js
Twig.extendFilter('foo', function (value) {
    return util.format(value);
});
```

After adding a filter you'll be able to use it in your templates:
`{{ value|foo }}`

**Comment by George02** [comment]
My bad that I didn't read the full documentation. Thanks mate !

**Comment by evgenius** [comment]
You're welcome :)
