### ISSUE TITLE
Feature request: Date format locale

### ISSUE THREAD

**Issue by Ashot-KR** [justjohn/twig.js#209]
It would be great to have configurable date format locale.  
I think, locales can be ported from [moment.js](https://github.com/moment/moment/tree/develop/locale)

**Comment by evgenius** [comment]
Hi @Ashot-KR ,

A locale-aware formatting is not a part of Twig.php core so I don't think it should be included into Twig.js.
It's included into the Intl extension: http://twig.sensiolabs.org/doc/extensions/intl.html
So in my opinion a possible solution could be creating a port of that extension.
