### ISSUE TITLE
twig with path return true

### ISSUE THREAD

**Issue by GibbsFrance** [justjohn/twig.js#212]
Hi,

When I want to test a render with data attribute, it works correctly. But when I want to use a file (with the path attribute), the function returns true : 

```javascript
var twig = require('twig').twig

var template = twig({
    data: "Hello !"
});
console.log(template); // Object Twig

var pTemplate = twig({
    path: "../views/mail/reset.twig"
});
console.log(pTemplate); // True
```

I looked at other reports (such as #37), but no information has helped me. If someone would have a solution, I will be grateful.

Thank you in advance and have a nice day.

**Comment by evgenius** [comment]
Hi @GibbsFrance ,

It's because `twig()` requires a callback when you use a `path` or `href` parameter:
```js
twig({
  path: path,
  load: function (template) { template.render(context); },
  error: function (err) { console.error(err); }
});
```

**Comment by GibbsFrance** [comment]
Thank you for the quick response! I had not seen this detail, it will be helpful.

Good evening

**Comment by evgenius** [comment]
You're welcome :)
