### ISSUE TITLE
Issue using set while extending a template

### ISSUE THREAD

**Issue by ismyhc** [justjohn/twig.js#213]
After upgrading from version 0.7.2 to 0.8 we are seeing a major issue using set while extending a template. Here is an example:

layout.html.twig
```
{% block body %}
	<div id="{{ pageId }}"></div>
{% endblock body %}
...
```

extended-layout.html.twig
```
{% extends 'layout' %}
{% set pageId = 'profile' %}
...
```

This worked as of 0.7.2.

**Comment by evgenius** [comment]
Thanks Davis,

Looks like this case wasn't covered with tests.
I'll try to fix it asap.

**Comment by evgenius** [comment]
@ismyhc, you can now upgrade to 0.8.1.
