### ISSUE TITLE
Runtime version of twig.js

### ISSUE THREAD

**Issue by webberig** [justjohn/twig.js#253]
In an effort to minimize the size of Javascript in our website, I've been looking into twig.js to create a 'runtime' version similar to the handlebars library (https://github.com/components/handlebars.js). The runtime version should only contain code needed to render templates, and is unable to tokenize or compile. 

I tried creating an additional build task that contains only a minimal part of the src/ folder. Unfortunately I'm stumped because of the code structure and perhaps some lack of understanding what each of the components actually does.

- /src/twig.compiler hardly contains any code, but it can be dropped without breaking twig.js runtime.
- The tokenizer is located inside twig.core.js, so there is no easy way to extract it, and it's very hard to determine the amount of bytes I could save.
- /src/twig.lib.js contains tons of code and it's unclear if they are used for tokenizing or being used for filters/functions implementations (I'm thinking the latter)

Before even thinking about creating a minimal runtime version of twig.js, I think that twig.core.js (and probably the other files) needs serious refactoring so the tokenizer, loaders, etc... must be seperated from the renderer.

@justjohn, what are your thoughts on this ? Do you think there is much to benefit from this ?

**Comment by plepe** [comment]
Duplicate of #229?

**Comment by webberig** [comment]
Yes, didn't notice due to different terminology. I'll keep watching the other issue.
