### ISSUE TITLE
TwigException: Cannot extend an inline template.

### ISSUE THREAD

**Issue by ebrian** [justjohn/twig.js#262]
Is there any reason why this shouldn't work?
```js
fs.readFile('template.twig', function(err, str) {
    var html = twig
        .twig({
            data: str.toString()
        })
        .render(data);
});
```

because I get:
```
Error parsing twig template undefined: 
TwigException: Cannot extend an inline template.
```

when this is in my template:
```
{% include 'partial/discussion/content/common_menu.twig' %}
```

and which taking it out, of course, fixes the issue.

Environment:
- node 0.10.36
- twig 0.8.2

I'm happy to hunt down the problem and fix it, but, I'm not really sure if it's a bug or by design.

**Comment by ebrian** [comment]
Workaround is to inline all of your includes, if anybody finds this post.

**Comment by kennethrapp** [comment]
Adding "allowInlineIncludes":true to the twig function loading the template worked for me.

**Comment by ebrian** [comment]
That did work, however adding it directly to my initial example like this:
```js
fs.readFile('template.twig', function(err, str) {
    var html = twig
        .twig({
            allowInlineIncludes: true,
            data: str.toString()
        })
        .render(data);
});
```

did not work. Instead I had to do it like this:
```js
var html = twig
    .twig({
        allowInlineIncludes: true,
        href: 'template.twig'
    })
    .render(data);
```

which I'm cool with, it's less code anyway.

Thanks for pointing me in the right direction.

**Comment by evgenius** [comment]
@ebrian Can we close this issue?

**Comment by ebrian** [comment]
@evgenius Yea, I think it can be closed. I eventually got it working the way it should be. Might be a docs issue rather than a code issue, because, under some configuration it does work properly.

**Comment by zachstronaut** [comment]
Hey... if you're using twig.js on both the front end and back end of your project, and you want to precompile your twig templates for the browser, and you are suddenly noticing this "Cannot extend an inline template" error when you are trying to use a template that calls extend or include... here's what I ended up doing for a solution:

    #!/bin/sh
    
    # Compile ./twig/ and its subfolders to ./twig-compiled/
    ./node_modules/.bin/twigjs --output twig-compiled/ ./twig/
    
    # Concatenate all of the compiled templates into a single ./js/templates.js file
    find ./twig-compiled -name *.js -print0 | xargs -0 -I file cat file > js/templates.js
    
    # Strip the twig-compiled/ prefix that the compile step stuck on all of your template ids
    # That way your relative extend and include paths you are using will keeping working
    sed -i '' -E 's/twig-compiled\///g' js/templates.js
    
    # Force allowInlineIncludes: true option for the precompiled templates
    # Otherwise twig.js is going to try to load templates off the server
    sed -i '' -E 's/(precompiled: true)/\1, allowInlineIncludes: true/g' js/templates.js

**Comment by ebrian** [comment]
@zachstronaut Nice. This is too clever for its own good. Thanks.

**Comment by kennethrapp** [comment]
@zachstronaut I
