### ISSUE TITLE
Escape filter missing strategy parameter

### ISSUE THREAD

**Issue by tremby** [justjohn/twig.js#263]
It looks like the escape filter is missing its strategy filter.

http://twig.sensiolabs.org/doc/filters/escape.html#escape

Is there any plan to implement this?

**Comment by plepe** [comment]
That's correct, it's currently not implemented. It shouldn't be too hard, though. Do you want to try your luck with it yourself? The escape filter can be found in src/twig.filters.js; also you will need to add a test case to prove that the filter works. This test will be in test/test.filters.js.

En-/disabling autoescape apparently is not supported yet. There seems to be some support for toggling autoescaping already, and I guess it wouldn't be too hard to implement.

**Comment by plepe** [comment]
Implemented in #289 - it would be nice if you could test before merging.

**Comment by tremby** [comment]
I had just a few minutes to look just now. One thing I noticed is that with 'css' a space seems to get converted to `\20 `, i.e. with a trailing space. Is that intended?

I'll have a closer look soon.

**Comment by tremby** [comment]
In fact everything it converts seems to have a trailing space. And I tried doing `var | escape('css') | escape('css')` and it looks like that leads to unexpected things too.

**Comment by plepe** [comment]
For reference I just tried Twig.php:
```twig
{{ 'X X'|escape('css') }}
{{ 'X X'|escape('css')|escape('css') }}
```

results in:

```
X\20 X
X\5C 20\20 X
```

The spaces seem intentional. In fact, here's the specification: http://www.w3.org/TR/CSS2/syndata.html#escaped-characters

**Comment by tremby** [comment]
Weird! OK. I should have time to do a quick bit of real-world testing tomorrow.

**Comment by plepe** [comment]
Btw, I tried to mimic Twig.php behaviour as closely as possible ...

**Comment by tremby** [comment]
At 2015-12-26 00:53:29 -0800, Stephan Bösch-Plepelits wrote:
> Btw, I tried to mimic Twig.php behaviour as closely as possible ...

As long as you pass whatever tests they have, I'm happy!

**Comment by plepe** [comment]
Can't really use Twig.php's tests, they look quite different (from the method). I just used http://twigfiddle.com/ to generate some complex strings to encode.

**Comment by plepe** [comment]
I just merged the branch, it's now in the new version 0.8.6.

If you find any bugs, please report :-)
