### ISSUE TITLE
Twig is not defined ? Browser

### ISSUE THREAD

**Issue by daslicht** [justjohn/twig.js#269]
Hello, 
when I try this code in teh Browser I get 'twig is not defined' ?

```
<script src="../twig.js"></script>
<script>
var template = twig({
    id: "list", // id is optional, but useful for referencing the template later
    data: "{% for value in list %}{{ value }}, {% endfor %}"
});

var output = template.render({
    list: ["one", "two", "three"]
});
</script>
```
what is missing?

**Comment by evgenius** [comment]
Hi @daslicht ,
Your code is correct so please make sure `twig.js` JS file is loaded correctly.
What does your network tab show?

**Comment by daslicht** [comment]
it is loaded :/

**Comment by daslicht** [comment]
https://jsbin.com/kosabi/2/edit?html,js,console,output

**Comment by daslicht** [comment]
got it !

**Comment by evgenius** [comment]
htttp -> https?
awesome :)

**Comment by daslicht** [comment]
was just a combination of typo and https :)

**Comment by daslicht** [comment]
heeh

**Comment by staminna** [comment]
I also have this issue. 

As per the examples in the documentation files I have:

app.js
views/index.twig
templates/posts.twig

In what file include script tag should be and how do I relate them to the HTML file?
Thanks.

**Comment by evgenius** [comment]
@staminna Your example is related to Node.js. If you're trying to run it in a browser, just include the twig.js script on a page where you want to render Twig templates.

**Comment by staminna** [comment]
@evgenius Thanks for quick reply.
I am trying to theme objects provided from Node.js and render them pretty with twig.js into a Drupal 8 (Twig) template. I have included twig.min.js into Drupal. Would you say I want to run in the process or Node.js?

**Comment by evgenius** [comment]
@staminna In this case you don't need Node.js. Just include `twig.min.js` as a script and use the `twig()` function as described here: https://github.com/justjohn/twig.js#browser-usage

**Comment by staminna** [comment]
@evgenius I see, but I need Node.js because it's the source of objects I want to theme. 
I also have javascript files, PHP and Twig templates I don't know where to put this. 
The HTML is dynamically generated. I have twig.min.js included in the header now but still,
If I add it into my javascript code, I keep getting the "twig is not defined" in the console.

**Comment by daslicht** [comment]
How to define inline templates using the script tag ?
??-->> https://jsbin.com/kosabi/edit?html,js,output  
please

**Comment by lmeurs** [comment]
I encountered the same issue when running v1.12.0 in the browser, with the same example code from the original post. For me the fix was replacing:

`var template = twig(...)`

with:

`var template = Twig.twig(...)`

**Comment by dmhendricks** [comment]
Thank you, @lmeurs, this is, indeed, required.

It may be a good idea to update the README.md [Browser Usage](https://github.com/twigjs/twig.js#browser-usage) example.
