### ISSUE TITLE
Markdown plugin/tag?

### ISSUE THREAD

**Issue by jordanlev** [justjohn/twig.js#271]
Curious if there's an existing "markdown" twig tag that works with twig.js, or if it's something I'd need to build myself. (Or perhaps some kind of in-between solution where I can make a twig tag that calls out to some other markdown js library?).

Thanks!

**Comment by plepe** [comment]
No, there is no such tag, and I think it shouldn't be part of the main library (it's also not part of Twig.php). Check the Wiki to learn how to extend Twig with custom functions, filters and tags:
https://github.com/justjohn/twig.js/wiki

**Comment by jordanlev** [comment]
In case someone wants it, I wrote a markdown tag that passes through the tag content to the 'marked' parser. It also takes into account the indentation level of the first line of markdown (so the markdown parser doesn't think that every line is a `pre` block).

```js
  var marked = required('marked');

  function twigMarkdownExtension(Twig) {
    Twig.exports.extendTag({
      type: "markdown",
      regex: /^markdown$/,
      next: ["endmarkdown"],
      open: true,
      parse: function (token, context, chain) {
        var output = Twig.parse.apply(this, [token.output, context]);

        var indentation = output.match(/^\s*/);
        indentation = (indentation && indentation.length) ? indentation[0] : '';
        if (indentation.length) {
          var lines = output.split(/\r?\n/);
          var regex = new RegExp('^' + indentation);
          for (var i = 0, len = lines.length; i < len; i++) {
            lines[i] = lines[i].replace(regex, '');
          }
          output = lines.join("\n");
        }

        output = marked(output);
        
        return {
          chain: chain,
          output: output
        };
      }
    });

    Twig.exports.extendTag({
      type: "endmarkdown",
      regex: /^endmarkdown$/,
      next: [ ],
      open: false
    });
  }
```

**Comment by plepe** [comment]
I created a page in the Wiki for a list of available extensions and used your markdown tag as first entry :-) Feel free to improve the entry.

https://github.com/justjohn/twig.js/wiki/Available-Extensions

I would suggest to create a repository for your extension and link there from the wiki page instead.

**Comment by jordanlev** [comment]
Great idea, done! Thanks.
