### ISSUE TITLE
Running tests in browser: arr.should.containEql is not a function

### ISSUE THREAD

**Issue by plepe** [justjohn/twig.js#281]
I'm currently trying the twig.js unit tests in different browsers. Beside a few small issues which I'll try to tackle soon, there's one problem which I can't figure out.

The tests for function "random" uses `should.containEql` to check whether the result is in the list of possible results. Apparently this function (containEql) is not available, when running the tests inside a browser (because the do work in node.js). I couldn't find any information about this on the interwebs ...

There are two versions of the resulting error message:

Mozilla Firefox 42, Chromium 47, Opera 12 report:
```
random ->
    should return a random item from a traversable or array
    arr.should.containEql is not a function
    @http://HOST/PATH/twig.js/test/test.functions.js:285:1
```

Safari (Windows), Gnome Webbrowser, XXXTerm report:
```
random ->
should return a random item from a traversable or array ‣
undefined is not a function (evaluating 'arr.should.containEql(twig({data: '{{ random(arr) }}'}).render({arr: arr}))')
http://HOST/PATH/twig.js/test/test.functions.js:285:42
```

I think that's exactly the same error, but a different message.

I haven't tested IE yet ...

**Comment by evgenius** [comment]
@plepe How do you run the tests in a browser? In particular how do you include `should.js`?

**Comment by plepe** [comment]
I was unsure myself, I've never used mocha or should.js before. I just browsed to the test/ directory (via https of course), and voila ...
