### ISSUE TITLE
url_encode doesnt appear to work

### ISSUE THREAD

**Issue by r3wt** [justjohn/twig.js#285]
`var args = {query:'test'};`

`{{'/user/search?q='~query|url_encode}}`

results in

`/user/search?q=test` instead of `%2Fuser%2Fsearch%3Fq%3Dtest`

**Comment by evgenius** [comment]
@r3wt It's expected behavior: http://twigfiddle.com/efjknw

**Comment by evgenius** [comment]
@r3wt This is doing what you wanted to get: `{{('/user/search?q='~query)|url_encode}}`

**Comment by r3wt** [comment]
thanks evgenius. never used the parens before
