### ISSUE TITLE
Passing a numbered string to the date filter results in date format as unix epoch (0)

### ISSUE THREAD

**Issue by Maelstrome26** [justjohn/twig.js#296]
`"123456789"|date('d-M-Y')` renders out as `01-Jan-1970`

Now of course people shouldn't really be passing in integers as strings but I come across this in passing, as my application API returned a string in this particular instance.

In PHP Twig, doing this the same way results in the proper date `29-Nov-1973 `.

**Comment by plepe** [comment]
Confirmed. Correct place to fix this bug is the strtotime function of phpjs. Will look into it.

**Comment by plepe** [comment]
If you want you could also try to fix this bug yourself and send a pull request. I might manage to do it in a few days ...

The source code is in src/twig.filters.js line 479 and following.

**Comment by plepe** [comment]
Fixed. Will be included in the next released and is already available if you compile twig.js yourself.

Note for reference: Timestamps don't reach the strtotime function.

**Comment by trajektorijus** [comment]
Same issue with this date format: "2015-11-19T17:02:04" which is sent by WordPress Rest API.
1970 is printed only on iOS.

**Comment by plepe** [comment]
@trajektorijus Which version of twig.js are you using?
