### ISSUE TITLE
Twig.renderFile is broken

### ISSUE THREAD

**Issue by sjuvonen** [justjohn/twig.js#302]
Inside Twig.exports.renderFile, variable **options** is defaulted to an empty object {} and right after this the code tries to access this object's sub properties (options.settings.views and 'twig options'), which will then cause errors like this:

> TypeError: Cannot read property 'views' of undefined (node_modules/twig/twig.js:6160:39

**Comment by createvibe** [comment]
I can definitely see the issue in the code.  Could provide a use case / example so I can test a fix for it?

**Comment by sjuvonen** [comment]
I don't know if you meant actual code or what, but I'm using Twig to render templates by calling the said function manually. That is, without configuring Twig in any way beforehand, if it makes a difference.

> twig.renderFile("/path/to/views/my-view.html", result => { /* more code */ })
> twig.renderFile("/path/to/views/my-view.html", {someData: "foo"}, result => { /* more code */ })

Basically it's easy to fix the two offending lines as follows, but I haven't used Twig.js before and didn't have time to implement test cases to see if the fix broke some other use-case.

> line 6160: base: (options.settings || {})['views'],
> line 6168: var view_options = (options.settings || {})['twig options'];

**Comment by createvibe** [comment]
Although I can see the code issue, I am unable to reproduce it.  Here is a test - http://code.runnable.com/Vqk-62bL7ZMavAkW/twig-js-test-express-integration-for-node-js-and-express-js

**Comment by createvibe** [comment]
It seems like the intent for renderFile was to be used with express, specifically.  Either the docblock needs to be changed or the function name.  I'm wondering if this function was ever intended to be use directly, as you are doing.  Hopefully my PR will fix the issues you are having.
