### ISSUE TITLE
Conflict with other twig templates

### ISSUE THREAD

**Issue by artlantis** [justjohn/twig.js#306]
Just want to know that have you ever used with other twig templates in same page? I mean, magento right now using twig in their .phtml files. So, is it possible to mix different platform in same page?

**Comment by plepe** [comment]
I'm using the same templates for rendering on the server side with Twig.php and on the client side with twig.js - works fine. But I think, this is not what you mean. I guess, as long as you have a way to tell which template uses which rendering engine, this should be fine?

**Comment by artlantis** [comment]
yes, exactly what I want to know but how? How we distunguish server side code with client side?

**Comment by plepe** [comment]
I don't really understand. Rendering is always a function call, either from a PHP (then you would call the Twig.php variant) or Twig.js from the client (in a browser) or server side (in nodejs). It's your code (or someone else's code), you (or someone else) have to know which variant you have to call.

If you are using Magento (I've never heard of Magento before, so I can't really tell), the best would be to ask them if it is possible to render templates with twig.js.

Maybe another try: could you explain in more detail what you want to achieve?

**Comment by artlantis** [comment]
Ok I just realized that had a mistaken. I thought how distinguish template placeholders with different renderer in the same page. But just came in my mind twig.js join in the scene after the server side code generated. Sorry about that. Thank you.
