### ISSUE TITLE
Disable view cache in express

### ISSUE THREAD

**Issue by aerze** [justjohn/twig.js#312]
I've tried setting `Twig.cache(false)` and `app.set('view cache', false)`.
And more importantly I can't find any clear documentation on the correct was to disable for development.

I'm using Express 4 and this code
```js
var Twig = require('twig');
Twig.cache(false);
...
app.set('views', '/views');
app.set("twig options", { strict_variables: false });
app.set('view engine', 'twig');
app.set('view cache', false);
```

**Comment by tremby** [comment]
I was looking for the same thing, but it worked for me as soon as I added `Twig.cache(false)` as you have above.

**Comment by micahgodbolt** [comment]
confirmed that `twig.cache(false);` works

**Comment by aerze** [comment]
I ended up using the `consolidate` library and the using `set('cache', false);`

```js
var cons = require('consolidate');
...
app.engine('html', cons.twig);
app.set('view engine', 'html');
app.set('views', myDir);
app.set('cache', false);
```
I think my error was setting `'view cache'` to `false` instead of `'cache'`

**Comment by tremby** [comment]
I didn't set that variable at all. Glad you got it working, though.
