### ISSUE TITLE
Gitter channel?

### ISSUE THREAD

**Issue by dave-irvine** [justjohn/twig.js#329]
Hi @plepe, any chance of this repo getting a gitter.im channel? Would be a good place to communicate about things like "when is 0.8.9 being released?" ;)

**Comment by plepe** [comment]
Never used gitter.im before, but let's give it a try :) I created a room: https://gitter.im/justjohn/twig.js

**Comment by dave-irvine** [comment]
Great, thanks. If you decide to keep it you can add a badge to the readme so people can find it.
