### ISSUE TITLE
Tizen TV and twig.js

### ISSUE THREAD

**Issue by danielhanzs** [justjohn/twig.js#334]
Hi there,

I added a little modification to the code to be able to run twig.js ajax template rendering on samsung tizen TV web based application.

On line 1367 added window.tizen to the if selection.

if (xmlhttp.status === 200 || ((window.cordova || window.tizen) && xmlhttp.status == 0)) {

On tizen the twig template xmlhttp status is also 0.

Have a nice day!

**Comment by plepe** [comment]
Don't you want to send a pull request? See the [contribution guidelines](https://github.com/justjohn/twig.js/wiki/Contributing) for reference ...

**Comment by danielhanzs** [comment]
Will try.
