### ISSUE TITLE
Twig - Expressjs (4+) not well supported for templating

### ISSUE THREAD

**Issue by newtonflash** [justjohn/twig.js#338]
When using twig with expressjs (4+), any change in template is not updated in browser. You need to manually restart the browser to see updates. 
Do you have a solution for this?

**Comment by createvibe** [comment]
Sounds like you are using cache.  Have you tried telling twig not to cache the templates?

Maybe we need an easy way to clear registry cache if you change a template file...

**Comment by newtonflash** [comment]
Hey,
Here is the snippet that I have in app.js 
//=======================
//app.engine('.html', require('twig').__express);  //does this exist in twig??? 
app.set('view engine', siteConfig.templateEngine);

app.set('view cache', false);

//=============================

I guess this is what you mean.

**Comment by createvibe** [comment]
Have you checked to see if Twig's cache is enabled?  Try calling `Twig.cache(false)`

**Comment by newtonflash** [comment]
Oh, thanks, it solved my problem. You can close this issue now.
