### ISSUE TITLE
template includes

### ISSUE THREAD

**Issue by conarwelsh** [justjohn/twig.js#73]
the PHP implementation does not allow relative includes, yet I cannot seem to get the JS version to do anything but relative includes.  If I am rendering a template that is in a sub-folder, and it is trying to include a template that is in a sub-folder at the same level, how would I go about this.

Is there someway I could avoid it running the relativePath function, and instead check if it starts with a '/' making it an absolute path?

**Comment by evgenius** [comment]
Looks like it was fixed in 0.6.
