### ISSUE TITLE
Twig.php: arrays can have a trailing , like in PHP

### ISSUE THREAD

**Issue by m-abs** [justjohn/twig.js#83]
In Twig.php's test/Twig/Tests/Fixtures/expressions/array.test

There is this structure:
```
{{
  [
    1,
    2,
  ]|join(',')
}}
```

It throws an error:
```
TwigException: Twig.expression.type.array.end cannot follow a Twig.expression.type.comma at template:5 near ']...'
```

However that structure is supported by Twig.php (according to the array.test)

**Comment by evgenius** [comment]
Fixed in https://github.com/justjohn/twig.js/commit/7a7e1bf9a3ff8f19fdc507f39965eab423649b22
